version: "3.1"
services:
  nginx:
    image: nginx:alpine
    container_name: billing.study-on.local
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
    ports:
      - "127.0.0.1:8001:80"
    links:
      - php
  php:
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1